source 'https://rubygems.org'

gem 'opal', '0.7.2'
gem 'opal-knockout', path: '..'
gem 'therubyracer'

source 'https://rails-assets.org' do
  gem 'rails-assets-knockoutjs', '3.3.0'
  gem 'rails-assets-knockout-validation', '2.0.3'
end