source 'https://rubygems.org'

gem 'opal-knockout', path: '..'
gem 'therubyracer'

source 'https://rails-assets.org' do
  gem 'rails-assets-knockoutjs', '~> 3.4.0'
  # gem 'rails-assets-knockout-validation', '~> 2.0.3'
end